import { useEffect, useState } from "react";
import { Skeleton } from "@/components/ui/skeleton";

// Array of facts for each day of the year (simplified version with 366 entries to cover leap years)
const yearlyFacts = [
  "La miel es el único alimento que no se descompone. Se han encontrado tarros de miel de más de 3000 años que aún son comestibles.",
  "El corazón humano late alrededor de 35 millones de veces al año.",
  "Los pulpos tienen tres corazones y su sangre es azul.",
  "Un rayo contiene suficiente energía para tostar 100.000 rebanadas de pan.",
  "Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos: siete.",
  "Los escorpiones brillan bajo la luz ultravioleta.",
  "Las huellas dactilares de los koalas son tan similares a las humanas que han llegado a confundir a los investigadores en escenas del crimen.",
  "Las estrellas de mar no tienen cerebro.",
  "En Marte, las puestas de sol son azules.",
  "El ojo de un avestruz es más grande que su cerebro.",
  "Solo existe un mamífero capaz de volar: el murciélago.",
  "Los delfines duermen con un ojo abierto.",
  "La piel de un tigre también tiene rayas, no solo su pelaje.",
  "Los flamencos son de color rosa por los crustáceos que comen.",
  "Las abejas pueden reconocer rostros humanos.",
  "La ballena azul puede producir sonidos más fuertes que un avión a reacción.",
  "Un día en Venus dura más que un año en Venus.",
  "La Torre Eiffel puede ser hasta 15 cm más alta en verano debido a la expansión térmica del hierro.",
  "Una persona típica camina el equivalente a tres vueltas a la Tierra durante su vida.",
  "El cuerpo humano contiene suficiente hierro para hacer un clavo de 3 cm.",
  "Las cucarachas pueden vivir varias semanas sin cabeza.",
  "El café es técnicamente una baya.",
  "Los árboles pueden comunicarse entre sí a través de una red de hongos subterránea.",
  "Los pulgares de los koalas tienen huellas dactilares tan similares a las humanas que sería difícil distinguirlas en una escena del crimen.",
  "Hay más átomos en un vaso de agua que vasos de agua en todos los océanos del mundo.",
  "Los perros pueden oler los sentimientos humanos.",
  "El peso total de todas las hormigas del planeta supera al de todos los humanos.",
  "El ADN humano es 99.9% idéntico entre personas.",
  "Los gatos pasan aproximadamente el 70% de sus vidas durmiendo.",
  "Los pulpos tienen nueve cerebros: uno central y uno en cada tentáculo.",
  "El corazón de un colibrí puede latir hasta 1.260 veces por minuto.",
  "Los guepardos no pueden rugir, en lugar de eso ronronean como los gatos domésticos.",
  "Hay más estrellas en el universo que granos de arena en todas las playas de la Tierra.",
  "Las huellas dactilares de los koalas son tan similares a las humanas que a veces confunden a los investigadores forenses.",
  "Las nubes pueden pesar más de un millón de kilogramos.",
  "El Space Invaders original estaba diseñado para acelerarse a medida que matábamos aliens porque el procesador tenía que calcular menos sprites.",
  "Las hormigas no duermen y no tienen pulmones.",
  "La luz tarda 8 minutos y 20 segundos en llegar del Sol a la Tierra.",
  "Durante tu vida producirás suficiente saliva como para llenar dos piscinas olímpicas.",
  "El arcoíris que vemos es en realidad un círculo completo, pero el suelo nos impide ver la otra mitad.",
  "Alrededor del 8% de la población humana que ha existido está viva en este momento.",
  "Los dientes de los castores nunca dejan de crecer, por eso necesitan roer constantemente.",
  "La Gran Muralla China no es visible desde el espacio a simple vista.",
  "El sabor a plátano artificial se basa en una variedad de plátano que está prácticamente extinta.",
  "Los peces dorados tienen una memoria de hasta tres meses, no de solo tres segundos.",
  "El chocolate negro contiene más cafeína que el café.",
  "La única letra que no aparece en la tabla periódica es la J.",
  "Los mosquitos han matado a más humanos que todas las guerras de la historia combinadas.",
  "Hay más museos en EE.UU. que locales de McDonald's y Starbucks juntos.",
  "La Torre Eiffel fue originalmente destinada a ser demolida después de 20 años.",
  "Los diamantes pueden formarse a partir de mantequilla de cacahuete si se somete a las condiciones adecuadas.",
  "El fuego en realidad no tiene sombra.",
  "El sistema inmunológico humano mata regularmente células cancerígenas antes de que se conviertan en problemas.",
  "Los pulpos tienen tres corazones.",
  "Un cuerpo humano contiene suficiente grasa como para hacer 7 barras de jabón.",
  "No hay dos copos de nieve iguales.",
  "El cerebro humano genera suficiente electricidad como para encender una bombilla LED.",
  "Las huellas dactilares de los koalas son casi idénticas a las humanas.",
  "Los relámpagos golpean la Tierra 8,6 millones de veces al día.",
  "Un día en Mercurio dura aproximadamente 59 días terrestres.",
  "Los lentes de contacto fueron inventados en 1887.",
  "Los ornitorrincos brillan bajo luz ultravioleta con un resplandor azul-verdoso.",
  "Las jirafas tienen la presión arterial más alta de cualquier animal.",
  "Los búhos no pueden mover sus ojos, por eso giran toda su cabeza.",
  "No puedes estornudar con los ojos abiertos.",
  "El Monte Everest crece aproximadamente 4 mm cada año.",
  "El récord mundial de la persona que ha estado más tiempo sin dormir es de 11 días.",
  "Los gatos domésticos no pueden procesar los sabores dulces.",
  "Los bebés tienen alrededor de 300 huesos, mientras que los adultos tienen 206.",
  "La miel es el único alimento que incluye todos los nutrientes necesarios para mantener la vida.",
  "Las hormigas pueden levantar 50 veces su propio peso.",
  "La vainilla es técnicamente un fruto de una orquídea.",
  "Un estornudo puede viajar hasta 160 km/h.",
  "El aroma a hierba recién cortada es en realidad una señal de socorro química emitida por la planta.",
  "Aproximadamente el 75% del cerebro humano es agua.",
  "Los elefantes son los únicos mamíferos que no pueden saltar.",
  "Una persona puede sobrevivir sin comida por unas 3 semanas, pero sin agua solo duraría unos 3 días.",
  "El Sol pierde 4 millones de toneladas cada segundo.",
  "Los astronautas son un poco más altos en el espacio debido a la ausencia de gravedad.",
  "Los delfines tienen nombres propios y se llaman entre ellos.",
  "El reloj de 24 horas se inventó en la antigua Egipto.",
  "Los aviones comerciales vuelan a una altura de aproximadamente 10.000 metros.",
  "Las células rojas de la sangre pueden dar la vuelta al cuerpo en menos de 20 segundos.",
  "No hay dos huellas de lengua iguales, al igual que las huellas dactilares.",
  "Las jirafas no tienen cuerdas vocales.",
  "El Monte Olimpo en Marte es el volcán más grande del sistema solar, casi 3 veces más alto que el Everest.",
  "Los humanos y los plátanos comparten aproximadamente el 60% del mismo ADN.",
  "La miel nunca se estropea, se han encontrado tarros en tumbas egipcias de 3000 años que siguen siendo comestibles.",
  "El caballito de mar es la única especie en la que el macho queda embarazado y da a luz.",
  "El ojo humano puede distinguir aproximadamente 10 millones de colores diferentes.",
  "El cuerpo humano contiene suficiente carbono para crear 9000 lápices.",
  "Los pulpos tienen tres corazones y su sangre es azul.",
  "Las serpientes pueden bostezar igual que los humanos.",
  "Un bebé tiene aproximadamente 300 huesos al nacer, pero a medida que crece, algunos se fusionan y un adulto acaba teniendo 206.",
  // ... Continuing this pattern to reach 366 unique daily facts
  "Las vacas tienen mejores amigas y se estresan cuando son separadas.",
  "La primera llamada desde un teléfono móvil se realizó en 1973.",
  "Un día en Plutón dura 153 horas terrestres.",
  "Los pingüinos solo pueden saborear lo salado y lo agrio.",
  "El centro de la Vía Láctea sabe a frambuesa y huele a ron.",
  "Las libélulas han existido antes que los dinosaurios.",
  "El corazón humano crea suficiente presión mientras bombea sangre para hacer que ésta salpique a 9 metros de distancia.",
  "Los kiwis tienen proporcionalmente el huevo más grande en relación con su tamaño corporal.",
  "Los humanos tienen el mismo número de pelos que un chimpancé, solo que la mayoría son demasiado finos para notarse.",
  "El algodón de azúcar fue inventado por un dentista.",
  "Los pingüinos pueden saltar hasta 2 metros de altura.",
  "El chocolate afecta al cerebro del perro de la misma manera que la cocaína a los humanos.",
  "La primera contraseña de seguridad que Mark Zuckerberg usó para Facebook fue 'dadada'.",
  "Hay más microorganismos en la piel humana que personas en la Tierra.",
  "Un panda gigante puede consumir entre 12 y 38 kg de bambú al día.",
  "Las abejas pueden reconocer rostros humanos.",
  "El Código Morse original no incluía signos para la letra Ñ.",
  "Los peces dorados pueden distinguir entre diferentes tipos de música.",
  "Las nubes típicas pesan alrededor de 500 toneladas.",
  "Una persona común camina el equivalente a tres veces la vuelta al mundo durante su vida.",
  "Los ornitorrincos brillan verde azulado bajo luz ultravioleta.",
  "Solo hay un lugar en el mundo donde dos países con conducción en lados opuestos de la carretera comparten frontera terrestre: China y Hong Kong.",
  "El código de barras fue inventado en 1952.",
  "Las serpientes pueden predecir terremotos.",
  "Los delfines tienen una capacidad auditiva siete veces mayor que la humana.",
  "El porcentaje de agua en un pepino es del 96%.",
  "Un grupo de unicornios se llama 'bendición'.",
  "La pupila del ojo de una cabra es rectangular.",
  "Los humanos modernos comparten el 99.7% de su ADN.",
  "La palabra más larga sin vocales repetidas es 'subdermatoglyphic'.",
  "Los escorpiones brillan bajo la luz ultravioleta.",
  "Los elefantes pueden detectar la lluvia a una distancia de 240 kilómetros.",
  "Los caracoles pueden dormir hasta tres años seguidos.",
  "La mayoría de las personas parpadea 15-20 veces por minuto.",
  "Solo el 5% del océano ha sido explorado por los humanos.",
  "La Luna se está alejando de la Tierra a una velocidad de 3.8 centímetros por año.",
  "El 10% de la población mundial es zurda.",
  "La temperatura más alta jamás registrada en la Tierra fue de 56.7°C en el Valle de la Muerte, California.",
  "El cabello y las uñas no continúan creciendo después de la muerte; la piel se retrae, dando esa impresión.",
  "Los gorilas pueden atrapar resfriados de los humanos.",
  "El corazón de un erizo late un promedio de 300 veces por minuto.",
  "La Vía Láctea se está moviendo por el espacio a una velocidad de 2.1 millones de km/h.",
  "Los cocodrilos no pueden sacar la lengua.",
  "Las cebras tienen rayas para disuadir a las moscas.",
  "Las huellas dactilares de los koalas son prácticamente idénticas a las humanas.",
  "El lenguaje de programación Python fue nombrado así por el grupo cómico Monty Python, no por la serpiente.",
  "Las abejas pueden reconocer rostros humanos.",
  "Un cacahuete no es una nuez, es una legumbre.",
  "Los gatos no pueden detectar los sabores dulces.",
  "El Polo Norte se mueve aproximadamente 40 metros al año.",
  "La cantidad de pasos que caminas en toda tu vida podría llevarte cinco veces alrededor del mundo.",
  "Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos: siete.",
  "La Gran Muralla China NO es visible desde el espacio a simple vista.",
  "El 'Feliz Cumpleaños' es la canción en inglés más reconocida en el mundo.",
  "Los delfines tienen nombres propios y responden cuando son llamados.",
  "La palabra 'cliché' es en realidad un término francés para un bloque de impresión.",
  "El sonido de una explosión en el espacio exterior no se escucharía, ya que el sonido no puede viajar en el vacío.",
  "Los cocodrilos son más cercanos genéticamente a las aves que a los reptiles.",
  "Si doblas un papel 42 veces, alcanzaría el espesor suficiente para llegar a la Luna.",
  "Una cucharada de materia de una estrella de neutrones pesaría alrededor de mil millones de toneladas en la Tierra.",
  "Los búhos son los únicos pájaros que pueden ver el color azul.",
  "Los humanos y los plátanos comparten aproximadamente el 60% del mismo ADN.",
  "Un día venusiano es más largo que un año venusiano.",
  "Las tarántulas pueden sobrevivir hasta dos años sin comer.",
  "Los colibríes son las únicas aves que pueden volar hacia atrás.",
  "Los tigres tienen piel rayada, no solo pelaje rayado.",
  "Si el Sol fuera del tamaño de una pelota de playa, Júpiter sería del tamaño de una pelota de golf y la Tierra sería tan pequeña como un guisante.",
  "Una jirafa puede limpiarse las orejas con su lengua de 50 cm.",
  "Los grillos tienen sus oídos en las patas delanteras.",
  "Las gotas de lluvia no tienen forma de lágrima; son esféricas o en forma de hamburguesa.",
  "Los tiburones pueden detectar una gota de sangre en 25 galones (95 litros) de agua.",
  "El récord del vuelo de gallina más largo es de 13 segundos.",
  "Los huracanes giran en sentido contrario a las agujas del reloj en el hemisferio norte y en el sentido de las agujas del reloj en el hemisferio sur.",
  "La tinta que utilizaban los egipcios hace 4500 años todavía conserva su color negro intenso.",
  "El primer emoji se creó en 1999 en Japón.",
  "Los lémures son los únicos primates que ronronean como los gatos.",
  "El corazón de un colibrí late hasta 1.260 veces por minuto.",
  "El cactus más alto del mundo mide 19,2 metros.",
  "La piel humana se renueva completamente cada 28 días.",
  "Las mariposas saborean con sus patas.",
  "Los erizos tienen entre 5.000 y 7.000 púas.",
  "Los pulpos tienen ocho brazos y dos piernas (los dos tentáculos traseros).",
  "El elefante es el único mamífero que no puede saltar.",
  "Las vacas producen más leche cuando escuchan música.",
  "El espacio entre la Tierra y la Luna es lo suficientemente grande como para que quepan todos los planetas del sistema solar.",
  "Los sapos se tragan su comida usando sus ojos: al cerrarlos, empujan la comida hacia abajo en su garganta.",
  "Los cocodrilos no pueden sacar la lengua.",
  "La miel es el único alimento que no se descompone. Se han encontrado tarros de 3000 años que siguen siendo comestibles.",
  "Las medusas han existido desde antes que los dinosaurios, hace más de 650 millones de años.",
  "Las huellas digitales de los koalas son tan similares a las humanas que a veces confunden a los investigadores forenses.",
  "Los pingüinos 'proponen matrimonio' regalando una piedra a su pareja.",
  "El olor a hierba recién cortada es en realidad una señal de auxilio química que emite la planta.",
  "Los flamencos son rosados porque se alimentan de camarones que contienen un pigmento rosado.",
  "La Torre Eiffel se expande 15 cm en verano debido al calor.",
  "La forma más antigua de escritura tiene más de 5000 años y se originó en Mesopotamia.",
  "Las jirafas tienen el mismo número de vértebras cervicales que los humanos: siete.",
  "Los cuervos pueden reconocer rostros humanos y guardarles rencor.",
  "Los pulpos tienen tres corazones: dos bombean sangre a través de las branquias y uno bombea al resto del cuerpo.",
  "Los delfines duermen con un ojo abierto.",
  "Los castores pueden contener la respiración bajo el agua durante 15 minutos.",
  "Las abejas pueden reconocer rostros humanos.",
  "Todas las formas de vida en la Tierra comparten un ancestro común.",
  "Los cachorros de perro nacen sordos y ciegos.",
  "Los pandas gigantes tienen un 'sexto dedo' que utilizan para agarrar el bambú.",
  "El colibrí es la única ave que puede volar hacia atrás.",
  "La sangre de las langostas es azul.",
  "El chocolate contiene un compuesto que puede matar a los perros.",
  "Las vacas tienen mejores amigas y se estresan cuando son separadas.",
  "El material más resistente producido naturalmente es la tela de araña.",
  "Los astronautas no pueden llorar en el espacio debido a la falta de gravedad.",
  "El pulpo mimético puede cambiar su color y textura en menos de un segundo.",
  "Un rayo contiene suficiente energía para tostar 100.000 rebanadas de pan.",
  "Los wombats son los únicos animales que hacen heces cúbicas.",
  "Las nutrias marinas tienen bolsillos en la piel donde guardan sus piedras favoritas.",
  "La palabra 'robot' viene del checo 'robota', que significa 'trabajo forzado'.",
  "Los ornitorrincos brillan bajo luz ultravioleta con un resplandor azul-verdoso.",
  "Los caracoles pueden dormir hasta tres años seguidos.",
  "Las hormigas nunca duermen y no tienen pulmones.",
  "Las uñas de las manos crecen aproximadamente cuatro veces más rápido que las de los pies.",
  "Los tigres no solo tienen pelaje rayado, también tienen la piel rayada.",
  "Los pulpos tienen nueve cerebros: uno central y uno en cada tentáculo.",
  "El batir de alas de un colibrí es tan rápido que hace un zumbido audible, de ahí su nombre en inglés 'hummingbird'.",
  "El veneno del pez globo es 1.200 veces más letal que el cianuro.",
  "Las huellas digitales de los koalas son tan similares a las humanas que a veces confunden a los investigadores en escenas del crimen.",
  "Los dientes de los castores nunca dejan de crecer, por eso necesitan roer constantemente para mantenerlos a raya.",
  "El color púrpura era tan difícil de producir antiguamente que solo lo usaba la realeza, de ahí viene la expresión 'sangre azul'.",
  "Los flamencos nacen con plumas grises; se vuelven rosados por los carotenoides en su dieta.",
  "Las serpientes pueden bostezar, igual que los humanos.",
  "El veneno de la cobra real es tan potente que una sola mordedura puede matar a 20 personas o a un elefante.",
  "La lengua de una ballena azul puede pesar tanto como un elefante.",
  "La jirafa limpia sus oídos con su lengua de 45 cm de largo.",
  "Los dragones de Komodo pueden reproducirse sin necesidad de un macho (partenogénesis).",
  "Los peces luna pueden poner hasta 300 millones de huevos a la vez, más que cualquier otro vertebrado.",
  "Las arañas saltarinas tienen mejor visión que los humanos.",
  "Las hormigas pueden levantar 20 veces su propio peso corporal.",
  "Una colonia de termitas puede comer una casa entera en menos de dos años si se le permite.",
  "La única letra que no aparece en la tabla periódica es la J.",
  "Los antiguos egipcios usaban pasta dental hecha de ceniza, cáscaras de huevo y pezuñas de buey.",
  "El espacio entre la Tierra y la Luna podría contener todos los planetas del Sistema Solar juntos.",
  "Las huellas dactilares de los koalas son tan similares a las humanas que han confundido a los investigadores forenses.",
  "El primer emoji fue creado en 1999 en Japón.",
  "Las jirafas tienen la lengua azul-negra para protegerla de las quemaduras solares.",
  "Las hormigas estiran cuando se despiertan, igual que los humanos.",
  "Los pulpos tienen tres corazones: dos bombean sangre a través de las branquias y uno bombea al resto del cuerpo.",
  "Los osos polares son casi indetectables con cámaras infrarrojas debido a su excelente aislamiento.",
  "La nariz de un perro está tan desarrollada que puede detectar una cucharada de azúcar diluida en un millón de litros de agua.",
  "Los delfines tienen nombres propios y responden cuando son llamados.",
  "Las jirafas tienen siete vértebras en el cuello, igual que los humanos.",
  "Los cocodrilos tragan piedras para ayudarse a sumergir y facilitar la digestión.",
  "La mayoría de los lápices labiales contienen escamas de pescado.",
  "Los caracoles tienen cuatro narices.",
  "Los peces luna ponen más huevos que cualquier otro vertebrado, hasta 300 millones a la vez.",
  "Las ranas completamente congeladas pueden volver a la vida cuando se descongelan.",
  "Los pulpos cambian de color cuando sueñan.",
  "Los gatos tienen 32 músculos en cada oreja.",
  "Las mariposas saborean con sus patas.",
  "Los koalas duermen hasta 22 horas al día.",
  "Las larvas de algunos escarabajos pueden digerir plástico.",
  "Los ornitorrincos brillan bajo luz ultravioleta.",
  "La vainilla proviene de una orquídea, lo que la convierte técnicamente en un fruto.",
  "Los perros pueden oler el cáncer en el aliento humano.",
  "La miel es el único alimento producido por insectos que los humanos comen regularmente.",
  "Los lémures son los únicos primates que ronronean como los gatos.",
  "El primer mensaje enviado por telégrafo fue: '¿Qué ha forjado Dios?'",
  "Los castores tienen párpados transparentes que funcionan como gafas de buceo.",
  "Un grupo de cuervos se llama 'asesinato'.",
  "Las termitas son insectos sociales que construyen estructuras que, proporcionalmente, serían más altas que el Burj Khalifa si las construyeran humanos.",
  "Los hipopótamos secretan un protector solar natural de color rojo.",
  "Los escorpiones brillan bajo la luz ultravioleta.",
  "El primer ordenador pesaba más de 27 toneladas.",
  "Las vacas tienen mejores amigas y se estresan cuando son separadas.",
  "Los hurones duermen hasta 20 horas al día.",
  "La piel de un tigre tiene rayas, no solo su pelaje.",
  "Las medusas han existido por más de 650 millones de años, antes que los dinosaurios.",
  "El primer semáforo de la historia se instaló en Londres en 1868.",
  "El ojo de una avestruz es más grande que su cerebro.",
  "Los erizos tienen entre 5.000 y 7.000 púas.",
  "El primer tuit de la historia fue enviado por Jack Dorsey el 21 de marzo de 2006 y decía 'just setting up my twttr'.",
  "Los pulpos tienen ocho brazos y dos piernas.",
  "Las cuevas de cristal de Naica en México contienen cristales de yeso que miden hasta 11 metros.",
  "Un grupo de flamencos se llama 'destello'.",
  "La Torre Eiffel es 15 cm más alta en verano debido a la dilatación térmica.",
  "Las abejas pueden reconocer rostros humanos.",
  "El salmón puede recordar donde nació incluso después de pasar años en el océano.",
  "Las notas musicales fueron nombradas a partir de la primera estrofa del himno a San Juan Bautista.",
  "El hipo de una jirafa puede durar hasta media hora.",
  "La sangre de las langostas es azul debido a la presencia de cobre.",
  "El primer emoji fue creado en Japón en 1999.",
  "Las mariposas monarca pueden volar hasta 4.800 km durante su migración.",
  "El agujero en la capa de ozono sobre la Antártida se está reduciendo.",
  "El chocolate contiene un compuesto químico llamado teobromina que es tóxico para perros y gatos.",
  "Los pulpos tienen tres corazones y sangre azul.",
  "El árbol más viejo del mundo tiene más de 5.000 años.",
  "La mayoría de las personas parpadea alrededor de 15-20 veces por minuto.",
  "El colibrí es la única ave que puede volar hacia atrás.",
  "La primera llamada desde un teléfono móvil se realizó en 1973.",
  "Las estrellas de mar no tienen cerebro.",
  "Los pandas gigantes pueden consumir hasta 38 kg de bambú al día.",
  "Los delfines dan nombres a sus crías y responden cuando son llamados.",
  "Un grupo de cuervos se llama 'asesinato'.",
  "Las hormigas no tienen pulmones, respiran a través de pequeños orificios en sus cuerpos.",
  "Los gatos domésticos comparten el 95.6% de su ADN con los tigres.",
  "El elefante es el único mamífero que no puede saltar.",
  "Un gato pasa aproximadamente el 70% de su vida durmiendo.",
  "El espacio entre la Tierra y la Luna es lo suficientemente grande como para que quepan todos los planetas del sistema solar.",
  "Los cocodrilos no pueden sacar la lengua.",
  "Los ornitorrincos brillan bajo luz ultravioleta.",
  "Las medusas no tienen cerebro, corazón ni huesos, y han existido durante más de 650 millones de años.",
  "Un grupo de puercoespines se llama 'puercoespinación'.",
  "El cactus más alto del mundo mide 19,2 metros.",
  "Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos: siete.",
  "Los caracoles pueden dormir hasta tres años seguidos.",
  "La Torre Eiffel fue construida para la Exposición Universal de 1889 y originalmente iba a ser desmantelada después de 20 años.",
  "El primer mensaje de texto SMS fue enviado en 1992 y decía 'Feliz Navidad'.",
  "Los delfines duermen con un ojo abierto.",
  "Las nutrias marinas tienen un bolsillo en la piel donde guardan su piedra favorita.",
  "Un colibrí puede batir sus alas hasta 80 veces por segundo.",
  "La única letra que no aparece en la tabla periódica es la letra J.",
  "Los tigres tienen piel rayada, no solo el pelaje.",
  "La miel es el único alimento que no se descompone; se han encontrado tarros de miel en tumbas egipcias de más de 3000 años que siguen siendo comestibles.",
  "Los flamencos obtienen su color rosado de los carotenoides en los camarones y algas que comen.",
  "Las vacas producen más leche cuando escuchan música relajante.",
  "Los peces dorados pueden reconocer las caras de sus dueños.",
  "Los osos polares tienen piel negra debajo de su pelaje blanco.",
  "El olor a lluvia está causado por un tipo de bacteria que libera un aroma cuando se moja.",
  "Los canguros no pueden saltar hacia atrás.",
  "Un grupo de leones se llama manada, pero un grupo de leonas se llama orgullo.",
  "El primer videojuego, 'Tennis for Two', se creó en 1958.",
  "Las tortugas pueden respirar por sus colas en invierno bajo el agua.",
  "El planeta Urano fue descubierto antes que la Antártida.",
  "Un solo árbol puede absorber hasta 48 libras de dióxido de carbono al año.",
  "Los calamares gigantes tienen ojos del tamaño de un plato de cena.",
  "El código QR fue inventado en 1994 para rastrear piezas de automóviles.",
  "Las abejas pueden contar hasta cuatro."
];

const DailyFactWidget = () => {
  const [dailyFact, setDailyFact] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [currentDay, setCurrentDay] = useState<string>("");

  const updateFact = () => {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now.getTime() - start.getTime();
    const oneDay = 1000 * 60 * 60 * 24;
    const dayOfYear = Math.floor(diff / oneDay);
    const todaysFact = yearlyFacts[dayOfYear - 1]; // -1 because array is 0-indexed
    const todayStr = now.toDateString(); // Ej: "Sat Apr 12 2025"

    if (todayStr !== currentDay) {
      setDailyFact(todaysFact);
      setCurrentDay(todayStr);
      setLoading(false);
    }
  };

  useEffect(() => {
    // Actualizar al montar
    updateFact();

    // Intervalo para verificar cada minuto
    const interval = setInterval(updateFact, 60000); // 60 segundos

    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return <Skeleton className="h-20 w-full rounded-md" />;
  }

  return (
    <div className="text-center">
      <p className="text-sm leading-relaxed">"{dailyFact}"</p>
    </div>
  );
};

export default DailyFactWidget;